language: python
cache: pip
python:
    - 3.8

services:
    - docker

install:
    - docker build -t python-barcode .
    - pip install pytest
    - pip install pipenv

script:
    - echo foo
    - pipenv shell
    - pipenv install -r requirements.txt
    - pytest